// Network configurations - easy to extend 
export const NETWORKS = [
  // Testnets
  {
    id: 'sepolia',
    name: 'Sepolia',
    chainId: 11155111,
    contractAddress: '0x8fCA96ae99D575e89f76D7E410A2B66AcfFb9683',
    rpcUrl: 'https://sepolia.infura.io/v3/bf6fd6deeb9d452880797d47f983dbcc',
    icon: 'SEP',
    logo: '/images/networks/ETH.svg',
    explorerUrl: 'https://sepolia.etherscan.io',
    currency: 'ETH',
    isTestnet: true
  },
  {
    id: 'base-sepolia',
    name: 'Base Sepolia',
    chainId: 84532,
    contractAddress: '0x9f27110Ec3b411B44Ec1c7AB9c964cB5eC8d33d2',
    rpcUrl: 'https://sepolia.base.org',
    icon: 'BASE',
    logo: '/images/networks/BASE.svg',
    explorerUrl: 'https://sepolia.basescan.org',
    currency: 'ETH',
    isTestnet: true
  },
  {
    id: 'optimism-sepolia',
    name: 'Optimism Sepolia',
    chainId: 11155420,
    contractAddress: '0x3c071d17561dc12437844575fa2426f8f28173c1',
    rpcUrl: 'https://sepolia.optimism.io',
    icon: 'OP',
    logo: '/images/networks/OP.svg',
    explorerUrl: 'https://sepolia-optimism.etherscan.io',
    currency: 'ETH',
    isTestnet: true
  },
  {
    id: 'monad-testnet',
    name: 'Monad Testnet',
    chainId: 10143,
    contractAddress: '0xC5464A200d5fE26B9EB78A22e0d3df8DF1971beB',
    rpcUrl: 'https://testnet-rpc.monad.xyz',
    icon: 'MON',
    logo: '/images/networks/MON.svg',
    explorerUrl: 'https://testnet.monadscan.com',
    currency: 'MON',
    isTestnet: true
  },
  {
    id: 'pharos-testnet',
    name: 'Pharos Testnet',
    chainId: 688688,
    contractAddress: '0xa1087a758742C8207Eb547fBC4A5B06d30A8526a',
    rpcUrl: 'https://testnet.dplabs-internal.com',
    icon: 'PHRS',
    logo: '/images/networks/PHRS.svg',
    explorerUrl: 'https://pharos-testnet.socialscan.io',
    currency: 'PHRS',
    isTestnet: true
  },
  {
    id: 'pharos-atlantic-testnet',
    name: 'Pharos Atlantic Testnet',
    chainId: 688689,
    contractAddress: '0x00bf43d03867434636c2397ada3d3f6d01f9d53b',
    rpcUrl: 'https://atlantic.dplabs-internal.com',
    icon: 'PHRS',
    logo: '/images/networks/PHRS.svg',
    explorerUrl: 'https://atlantic.pharosscan.xyz',
    currency: 'PHRS',
    isTestnet: true
  },
  {
    id: 'rise-testnet',
    name: 'Rise Testnet',
    chainId: 11155931,
    contractAddress: '0x370f35A28797A17603E0fbD5df6010272b1006FE',
    rpcUrl: 'https://testnet.riselabs.xyz',
    icon: 'RISE',
    logo: '/images/networks/RISE.svg',
    explorerUrl: 'https://explorer.testnet.riselabs.xyz',
    currency: 'ETH',
    isTestnet: true
  },
  {
    id: 'neura-protocol',
    name: 'Neura Testnet',
    chainId: 267,
    contractAddress: '0xD71caE47F4B4C800E82d9613BCe0f1E40Ae4932e',
    rpcUrl: 'https://testnet.rpc.neuraprotocol.io/',
    icon: 'ANKR',
    logo: '/images/networks/ANKR.svg',
    explorerUrl: 'https://testnet-blockscout.infra.neuraprotocol.io',
    currency: 'ANKR',
    isTestnet: true
  },
  {
    id: 'jovay-testnet',
    name: 'Jovay Testnet',
    chainId: 2019775,
    contractAddress: '0xd0c205e3c704595113fb8006379edd1bc89b2a17',
    rpcUrl: 'https://api.zan.top/public/jovay-testnet',
    icon: 'JOVAY',
    logo: '/images/networks/JOVAY.svg',
    explorerUrl: 'https://sepolia-explorer.jovay.io',
    currency: 'ETH',
    isTestnet: true
  },
  {
    id: 'giwa-testnet',
    name: 'Giwa Testnet',
    chainId: 91342,
    contractAddress: '0x0216f955f5062913cac97a95F28D57570ae3c9c1',
    rpcUrl: 'https://sepolia-rpc.giwa.io',
    icon: 'GIWA',
    logo: '/images/networks/GIWA.svg',
    explorerUrl: 'https://sepolia-explorer.giwa.io',
    currency: 'ETH',
    isTestnet: true
  },
  {
    id: 'kiteai-testnet',
    name: 'KiteAI Testnet',
    chainId: 2368,
    contractAddress: '0xf890a35d2f3c76182a7f1db593da78d4a389d257',
    rpcUrl: 'https://rpc-testnet.gokite.ai',
    icon: 'GOKITE',
    logo: '/images/networks/GOKITE.svg',
    explorerUrl: 'https://testnet.kitescan.ai',
    currency: 'GOKITE',
    isTestnet: true
  },
  {
    id: 'sandchain-testnet',
    name: 'SANDchain Testnet (Silica)',
    chainId: 6252,
    contractAddress: '0xD71caE47F4B4C800E82d9613BCe0f1E40Ae4932e',
    rpcUrl: 'https://sandchain-rpc.caldera.xyz/http',
    icon: 'SAND',
    logo: '/images/networks/SAND.svg',
    explorerUrl: 'https://sandchain-explorer.caldera.xyz',
    currency: 'SAND',
    isTestnet: true
  },
  {
    id: 'iopn-testnet',
    name: 'IOPn Testnet',
    chainId: 984,
    contractAddress: '0xD71caE47F4B4C800E82d9613BCe0f1E40Ae4932e',
    rpcUrl: 'https://testnet-rpc.iopn.tech',
    icon: 'OPN',
    logo: '/images/networks/OPN.svg',
    explorerUrl: 'https://testnet.iopn.tech',
    currency: 'OPN',
    isTestnet: true
  },
  {
    id: 'arc-testnet',
    name: 'Arc Testnet',
    chainId: 5042002,
    contractAddress: '0xd0c205e3C704595113FB8006379EDd1Bc89B2A17',
    rpcUrl: 'https://rpc.testnet.arc.network',
    icon: 'ARC',
    logo: '/images/networks/ARC.svg',
    explorerUrl: 'https://testnet.arcscan.app',
    currency: 'USDC',
    isTestnet: true
  },
  {
    id: 'stable-testnet',
    name: 'Stable Chain Testnet',
    chainId: 2201,
    contractAddress: '0xd0c205e3C704595113FB8006379EDd1Bc89B2A17',
    rpcUrl: 'https://rpc.testnet.stable.xyz',
    icon: 'STABLE',
    logo: '/images/networks/STABLE.svg',
    explorerUrl: 'https://testnet.stablescan.xyz',
    currency: 'gUSDT',
    isTestnet: true
  },
  // Mainnets
  {
    id: 'base',
    name: 'Base',
    chainId: 8453,
    contractAddress: '0xefbc854f51cbb80ccbe12c69da179d6901978f6c',
    rpcUrl: 'https://mainnet.base.org',
    icon: 'BASE',
    logo: '/images/networks/BASE.svg',
    explorerUrl: 'https://basescan.org',
    currency: 'ETH',
    isTestnet: false
  },
  {
    id: 'optimism',
    name: 'Optimism',
    chainId: 10,
    contractAddress: '0xC1225a891ecCEAF5e0899e9656FaeE10D0f62eF7',
    rpcUrl: 'https://optimism-rpc.publicnode.com',
    icon: 'OP',
    logo: '/images/networks/OP.svg',
    explorerUrl: 'https://explorer.optimism.io',
    currency: 'ETH',
    isTestnet: false
  },
  {
    id: 'unichain',
    name: 'Unichain',
    chainId: 130,
    contractAddress: '0xa7877CDF570BEbdf949CD9eC1147cf5c3241A380',
    rpcUrl: 'https://unichain-rpc.publicnode.com',
    icon: 'UNI',
    logo: '/images/networks/UNI.svg',
    explorerUrl: 'https://uniscan.xyz',
    currency: 'ETH',
    isTestnet: false
  },
  {
    id: 'celo',
    name: 'Celo',
    chainId: 42220,
    contractAddress: '0xB2bcF4f2fed7F933255A604F36e5A713dD30425E',
    rpcUrl: 'https://celo.drpc.org',
    icon: 'CELO',
    logo: '/images/networks/CELO.svg',
    explorerUrl: 'https://celoscan.io',
    currency: 'CELO',
    isTestnet: false
  },
  {
    id: 'ink',
    name: 'Ink',
    chainId: 57073,
    contractAddress: '0x2b426387571C3e31b3C9A3C5A91dbeF5CEa64143',
    rpcUrl: 'https://rpc-qnd.inkonchain.com',
    icon: 'INK',
    logo: '/images/networks/INK.svg',
    explorerUrl: 'https://explorer.inkonchain.com',
    currency: 'ETH',
    isTestnet: false
  },
  {
    id: 'worldchain',
    name: 'World Chain',
    chainId: 480,
    contractAddress: '0x55c7d6ce1d1f55d332b225002d71933c8ab18772',
    rpcUrl: 'https://worldchain.drpc.org',
    icon: 'WORLD',
    logo: '/images/networks/WORLD.svg',
    explorerUrl: 'https://worldscan.org',
    currency: 'ETH',
    isTestnet: false
  },
  {
    id: 'lisk',
    name: 'Lisk',
    chainId: 1135,
    contractAddress: '0x551872486F03DD194c40c2249a79f080c1e7Cd13',
    rpcUrl: 'https://lisk.drpc.org',
    icon: 'LISK',
    logo: '/images/networks/LISK.svg',
    explorerUrl: 'https://blockscout.lisk.com',
    currency: 'ETH',
    isTestnet: false
  },
  {
    id: 'linea',
    name: 'Linea',
    chainId: 59144,
    contractAddress: '0xda634574ea8b5ae57d3baf4744c50b78653aaf25',
    rpcUrl: 'https://rpc.linea.build',
    icon: 'LINEA',
    logo: '/images/networks/LINEA.svg',
    explorerUrl: 'https://lineascan.build',
    currency: 'ETH',
    isTestnet: false
  },
  {
    id: 'monad',
    name: 'Monad',
    chainId: 143,
    contractAddress: '0xd0c205e3C704595113FB8006379EDd1Bc89B2A17',
    rpcUrl: 'https://rpc.monad.xyz',
    icon: 'MON',
    logo: '/images/networks/MON.svg',
    explorerUrl: 'https://monadscan.com',
    currency: 'MON',
    isTestnet: false
  },
  {
    id: 'arbitrum',
    name: 'Arbitrum',
    chainId: 42161,
    contractAddress: '0x4b1b3c8A09B82aDbC93d8f3897B384b5f55A2B7a',
    rpcUrl: 'https://arbitrum.rpc.subquery.network/public',
    icon: 'ARB',
    logo: '/images/networks/ARB.svg',
    explorerUrl: 'https://arbiscan.io',
    currency: 'ARB',
    isTestnet: false
  },
  {
    id: 'plume',
    name: 'Plume',
    chainId: 98866,
    contractAddress: '0x4A6814b1E0c0EE505665E819a4317cc12C72DeBF',
    rpcUrl: 'https://rpc.plume.org',
    icon: 'PLUME',
    logo: '/images/networks/PLUME.svg',
    explorerUrl: 'https://explorer.plume.org',
    currency: 'PLUME',
    isTestnet: false
  },
  {
    id: 'hyperevm',
    name: 'HyperEVM',
    chainId: 999,
    contractAddress: '0x790b0C531889e8B5E8dAE48914CB33fc90b7E3a6',
    rpcUrl: 'https://hyperliquid.drpc.org',
    icon: 'HYPE',
    logo: '/images/networks/HYPE.svg',
    explorerUrl: 'https://www.hyperscan.com',
    currency: 'HYPE',
    isTestnet: false
  },
  {
    id: 'soneium',
    name: 'Soneium',
    chainId: 1868,
    contractAddress: '0x6732D612b2e9DeEb3DA2BB1221fBe6d2428175E1',
    rpcUrl: 'https://rpc.soneium.org',
    icon: 'SONEIUM',
    logo: '/images/networks/SONEIUM.svg',
    explorerUrl: 'https://soneium.blockscout.com',
    currency: 'ETH',
    isTestnet: false
  },
  {
    id: 'katana',
    name: 'Katana',
    chainId: 747474,
    contractAddress: '0x200A33143a4867c292fc8686E0B44dBe30Da6E5d',
    rpcUrl: 'https://rpc.katana.network',
    icon: 'KAT',
    logo: '/images/networks/KAT.svg',
    explorerUrl: 'https://explorer.katanarpc.com/',
    currency: 'ETH',
    isTestnet: false
  },
  {
    id: 'lens',
    name: 'Lens Chain',
    chainId: 232,
    contractAddress: '0xC383EA1256c8E04b3973B872d469888D47B19c34',
    rpcUrl: 'https://rpc.lens.xyz',
    icon: 'LENS',
    logo: '/images/networks/LENS.svg',
    explorerUrl: 'https://explorer.lens.xyz',
    currency: 'GHO',
    isTestnet: false
  },
  {
    id: 'zora',
    name: 'Zora',
    chainId: 7777777,
    contractAddress: '0x6eF5A563e26a7C898014C15ad866e75014E3A8BE',
    rpcUrl: 'https://zora.drpc.org',
    icon: 'ZORA',
    logo: '/images/networks/ZORA.svg',
    explorerUrl: 'https://zorascan.xyz',
    currency: 'ETH',
    isTestnet: false
  },
  {
    id: 'plasma',
    name: 'Plasma',
    chainId: 9745,
    contractAddress: '0xa68C670133b7b8178ec43Eb01d93be6E5C3B65A8',
    rpcUrl: 'https://rpc.plasma.to',
    icon: 'XPL',
    logo: '/images/networks/XPL.svg',
    explorerUrl: 'https://plasmascan.to',
    currency: 'XPL',
    isTestnet: false
  },
  {
    id: '0g',
    name: '0G',
    chainId: 16661,
    contractAddress: '0xd71cae47f4b4c800e82d9613bce0f1e40ae4932e',
    rpcUrl: 'https://evmrpc.0g.ai',
    icon: '0G',
    logo: '/images/networks/0G.svg',
    explorerUrl: 'https://chainscan.0g.ai',
    currency: '0G',
    isTestnet: false
  },
  {
    id: 'apechain',
    name: 'ApeChain',
    chainId: 33139,
    contractAddress: '0xDf520F324a5061A447084cF159037F35Fb2C4C89',
    rpcUrl: 'https://rpc.apechain.com',
    icon: 'APE',
    logo: '/images/networks/APE.svg',
    explorerUrl: 'https://apescan.io',
    currency: 'APE',
    isTestnet: false
  },
  {
    id: 'somnia',
    name: 'Somnia',
    chainId: 5031,
    contractAddress: '0x00Bf43d03867434636c2397AdA3D3f6d01f9d53B',
    rpcUrl: 'https://api.infra.mainnet.somnia.network',
    icon: 'SOMI',
    logo: '/images/networks/SOMI.svg',
    explorerUrl: 'https://explorer.somnia.network',
    currency: 'SOMI',
    isTestnet: false
  },
  {
    id: 'haust',
    name: 'Haust Network',
    chainId: 3864,
    contractAddress: '0xd0c205e3C704595113FB8006379EDd1Bc89B2A17',
    rpcUrl: 'https://haust-network-rpc.eu-north-2.gateway.fm',
    icon: 'HAUST',
    logo: '/images/networks/HAUST.svg',
    explorerUrl: 'https://haustscan.com',
    currency: 'HAUST',
    isTestnet: false
  },
  {
    id: 'intuition',
    name: 'Intuition',
    chainId: 1155,
    contractAddress: '0x123Be1873eA508F6EEC32731Ac3dd20908697596',
    rpcUrl: 'https://rpc.intuition.systems',
    icon: 'TRUST',
    logo: '/images/networks/TRUST.svg',
    explorerUrl: 'https://explorer.intuition.systems/',
    currency: 'TRUST',
    isTestnet: false
  }
];

// Updated ABI for HelloWorld contract
export const CONTRACT_ABI = [
  "function sayHello() external",
  "function canSayHello(address user) external view returns (bool)",
  "function getCurrentDay() external view returns (uint256)",
  "function lastHelloDay(address) external view returns (uint256)",
  "function lastHello(address) external view returns (uint256)",
  "function totalHellos(address) external view returns (uint256)",
  "function currentStreak(address) external view returns (uint256)",
  "function getUserStats(address user) external view returns (uint256 _lastHello, uint256 _totalHellos, uint256 _currentStreak, bool _canSayHello)",
  "function getUserInfo(address user) external view returns (uint256 _lastHelloDay, uint256 _currentDay, uint256 _lastHello, uint256 _totalHellos, uint256 _currentStreak, bool _canSayHello)",
  "function timeUntilNextHello(address user) external view returns (uint256)",
  "function timeUntilMidnight() external view returns (uint256)"
];
