// Network configurations - easy to extend 
export const NETWORKS = [
  // Testnets
  {
    id: 'sepolia',
    name: 'Sepolia',
    chainId: 11155111,
    contractAddress: '0x8fCA96ae99D575e89f76D7E410A2B66AcfFb9683',
    rpcUrl: 'https://sepolia.infura.io/v3/bf6fd6deeb9d452880797d47f983dbcc',
    icon: 'SEP',
    logo: '/images/networks/ETH.svg',
    explorerUrl: 'https://sepolia.etherscan.io',
    currency: 'ETH',
    isTestnet: true
  },
  {
    id: 'base-sepolia',
    name: 'Base Sepolia',
    chainId: 84532,
    contractAddress: '0x9f27110Ec3b411B44Ec1c7AB9c964cB5eC8d33d2',
    rpcUrl: 'https://sepolia.base.org',
    icon: 'BASE',
    logo: '/images/networks/BASE.svg',
    explorerUrl: 'https://sepolia.basescan.org',
    currency: 'ETH',
    isTestnet: true
  },
  {
    id: 'optimism-sepolia',
    name: 'Optimism Sepolia',
    chainId: 11155420,
    contractAddress: '0x3c071d17561dc12437844575fa2426f8f28173c1',
    rpcUrl: 'https://sepolia.optimism.io',
    icon: 'OP',
    logo: '/images/networks/OP.svg',
    explorerUrl: 'https://sepolia-optimism.etherscan.io',
    currency: 'ETH',
    isTestnet: true
  },
  {
    id: 'monad-testnet',
    name: 'Monad Testnet',
    chainId: 10143,
    contractAddress: '0xC5464A200d5fE26B9EB78A22e0d3df8DF1971beB',
    rpcUrl: 'https://testnet-rpc.monad.xyz',
    icon: 'MON',
    logo: '/images/networks/MON.svg',
    explorerUrl: 'https://testnet.monadscan.com/',
    currency: 'MON',
    isTestnet: true
  },
  {
    id: 'pharos-testnet',
    name: 'Pharos Testnet',
    chainId: 688688,
    contractAddress: '0xa1087a758742C8207Eb547fBC4A5B06d30A8526a',
    rpcUrl: 'https://testnet.dplabs-internal.com',
    icon: 'PHRS',
    logo: '/images/networks/PHRS.svg',
    explorerUrl: 'https://pharos-testnet.socialscan.io/',
    currency: 'PHRS',
    isTestnet: true
  },
  {
    id: 'pharos-atlantic-testnet',
    name: 'Pharos Atlantic Testnet',
    chainId: 688689,
    contractAddress: '0x00bf43d03867434636c2397ada3d3f6d01f9d53b',
    rpcUrl: 'https://atlantic.dplabs-internal.com',
    icon: 'PHRS',
    logo: '/images/networks/PHRS.svg',
    explorerUrl: 'https://atlantic.pharosscan.xyz/',
    currency: 'PHRS',
    isTestnet: true
  },
  {
    id: 'rise-testnet',
    name: 'Rise Testnet',
    chainId: 11155931,
    contractAddress: '0x370f35A28797A17603E0fbD5df6010272b1006FE',
    rpcUrl: 'https://testnet.riselabs.xyz',
    icon: 'RISE',
    logo: '/images/networks/RISE.svg',
    explorerUrl: 'https://explorer.testnet.riselabs.xyz/',
    currency: 'ETH',
    isTestnet: true
  },
  {
    id: 'megaeth-testnet',
    name: 'Megaeth Testnet',
    chainId: 6342,
    contractAddress: '0xc87347a4e46ad9d0809df41db6802809d7086b2e',
    rpcUrl: 'https://carrot.megaeth.com/rpc',
    icon: 'MEGA',
    logo: '/images/networks/MEGA.svg',
    explorerUrl: 'https://web3.okx.com/ru/explorer/megaeth-testnet',
    currency: 'ETH',
    isTestnet: true
  },
  {
    id: 'neura-protocol',
    name: 'Neura Testnet',
    chainId: 267,
    contractAddress: '0xD71caE47F4B4C800E82d9613BCe0f1E40Ae4932e',
    rpcUrl: 'https://testnet.rpc.neuraprotocol.io/',
    icon: 'ANKR',
    logo: '/images/networks/ANKR.svg',
    explorerUrl: 'https://testnet-blockscout.infra.neuraprotocol.io/',
    currency: 'ANKR',
    isTestnet: true
  },
  {
    id: 'haust-testnet-network',
    name: 'Haust Testnet Network',
    chainId: 1523903251,
    contractAddress: '0x3480fF98c739cFA0015C5f02fbe37C7C92E04D10',
    rpcUrl: 'https://rpc-testnet.haust.app',
    icon: 'HAUST',
    logo: '/images/networks/HAUST.svg',
    explorerUrl: 'https://explorer-testnet.haust.app/',
    currency: 'HAUST',
    isTestnet: true
  },
  {
    id: 'jovay-testnet',
    name: 'Jovay Testnet',
    chainId: 2019775,
    contractAddress: '0xd0c205e3c704595113fb8006379edd1bc89b2a17',
    rpcUrl: 'https://api.zan.top/public/jovay-testnet',
    icon: 'JOVAY',
    logo: '/images/networks/JOVAY.svg',
    explorerUrl: 'https://sepolia-explorer.jovay.io/',
    currency: 'ETH',
    isTestnet: true
  },
  // Mainnets
  {
    id: 'base',
    name: 'Base',
    chainId: 8453,
    contractAddress: '0xefbc854f51cbb80ccbe12c69da179d6901978f6c',
    rpcUrl: 'https://mainnet.base.org',
    icon: 'BASE',
    logo: '/images/networks/BASE.svg',
    explorerUrl: 'https://basescan.org',
    currency: 'ETH',
    isTestnet: false
  },
  {
    id: 'optimism',
    name: 'Optimism',
    chainId: 10,
    contractAddress: '0xC1225a891ecCEAF5e0899e9656FaeE10D0f62eF7',
    rpcUrl: 'https://optimism-rpc.publicnode.com',
    icon: 'OP',
    logo: '/images/networks/OP.svg',
    explorerUrl: 'https://explorer.optimism.io/',
    currency: 'ETH',
    isTestnet: false
  },
  {
    id: 'unichain',
    name: 'Unichain',
    chainId: 130,
    contractAddress: '0xa7877CDF570BEbdf949CD9eC1147cf5c3241A380',
    rpcUrl: 'https://unichain-rpc.publicnode.com',
    icon: 'UNI',
    logo: '/images/networks/UNI.svg',
    explorerUrl: 'https://uniscan.xyz/',
    currency: 'ETH',
    isTestnet: false
  },
  {
    id: 'celo',
    name: 'Celo',
    chainId: 42220,
    contractAddress: '0xB2bcF4f2fed7F933255A604F36e5A713dD30425E',
    rpcUrl: 'https://celo.drpc.org',
    icon: 'CELO',
    logo: '/images/networks/CELO.svg',
    explorerUrl: 'https://celoscan.io/',
    currency: 'CELO',
    isTestnet: false
  },
  {
    id: 'ink',
    name: 'Ink',
    chainId: 57073,
    contractAddress: '0x2b426387571C3e31b3C9A3C5A91dbeF5CEa64143',
    rpcUrl: 'https://rpc-qnd.inkonchain.com',
    icon: 'INK',
    logo: '/images/networks/INK.svg',
    explorerUrl: 'https://explorer.inkonchain.com/',
    currency: 'ETH',
    isTestnet: false
  },
  {
    id: 'worldchain',
    name: 'World Chain',
    chainId: 480,
    contractAddress: '0x55c7d6ce1d1f55d332b225002d71933c8ab18772',
    rpcUrl: 'https://worldchain.drpc.org',
    icon: 'WORLD',
    logo: '/images/networks/WORLD.svg',
    explorerUrl: 'https://worldscan.org/',
    currency: 'ETH',
    isTestnet: false
  },
  {
    id: 'lisk',
    name: 'Lisk',
    chainId: 1135,
    contractAddress: '0x551872486F03DD194c40c2249a79f080c1e7Cd13',
    rpcUrl: 'https://lisk.drpc.org',
    icon: 'LISK',
    logo: '/images/networks/LISK.svg',
    explorerUrl: 'https://blockscout.lisk.com/',
    currency: 'ETH',
    isTestnet: false
  },
  {
    id: 'plume',
    name: 'Plume',
    chainId: 98866,
    contractAddress: '0x4A6814b1E0c0EE505665E819a4317cc12C72DeBF',
    rpcUrl: 'https://rpc.plume.org',
    icon: 'PLUME',
    logo: '/images/networks/PLUME.svg',
    explorerUrl: 'https://explorer.plume.org/',
    currency: 'PLUME',
    isTestnet: false
  },
  {
    id: 'hyperevm',
    name: 'HyperEVM',
    chainId: 999,
    contractAddress: '0x790b0C531889e8B5E8dAE48914CB33fc90b7E3a6',
    rpcUrl: 'https://hyperliquid.drpc.org',
    icon: 'HYPE',
    logo: '/images/networks/HYPE.svg',
    explorerUrl: 'https://www.hyperscan.com/',
    currency: 'HYPE',
    isTestnet: false
  },
  {
    id: 'soneium',
    name: 'Soneium',
    chainId: 1868,
    contractAddress: '0x6732D612b2e9DeEb3DA2BB1221fBe6d2428175E1',
    rpcUrl: 'https://rpc.soneium.org',
    icon: 'SONEIUM',
    logo: '/images/networks/SONEIUM.svg',
    explorerUrl: 'https://soneium.blockscout.com/',
    currency: 'ETH',
    isTestnet: false
  },
  {
    id: 'katana',
    name: 'Katana',
    chainId: 747474,
    contractAddress: '0x200A33143a4867c292fc8686E0B44dBe30Da6E5d',
    rpcUrl: 'https://rpc.katana.network',
    icon: 'KAT',
    logo: '/images/networks/KAT.svg',
    explorerUrl: 'https://explorer.katanarpc.com/',
    currency: 'ETH',
    isTestnet: false
  }
];

// Updated ABI for HelloWorld contract
export const CONTRACT_ABI = [
  "function sayHello() external",
  "function canSayHello(address user) external view returns (bool)",
  "function getCurrentDay() external view returns (uint256)",
  "function lastHelloDay(address) external view returns (uint256)",
  "function lastHello(address) external view returns (uint256)",
  "function totalHellos(address) external view returns (uint256)",
  "function currentStreak(address) external view returns (uint256)",
  "function getUserStats(address user) external view returns (uint256 _lastHello, uint256 _totalHellos, uint256 _currentStreak, bool _canSayHello)",
  "function getUserInfo(address user) external view returns (uint256 _lastHelloDay, uint256 _currentDay, uint256 _lastHello, uint256 _totalHellos, uint256 _currentStreak, bool _canSayHello)",
  "function timeUntilNextHello(address user) external view returns (uint256)",
  "function timeUntilMidnight() external view returns (uint256)"
];